@startuml
title Механика работы метода создания заявки на банковскую гарантию

skinparam activity {
  startColor green
  endColor red
  stopColor red
}

|Клиент|
start
:Создание заявки;
repeat 
:Ввод данных по заявке \n (контракт, площадка размещения, сумма, срок)
POST/orders;

|Система Банковской гарантии|
:Валидация введенных данных;
:Запрос данных о контракте в ЕИС
Get/contracts/{contractID};
if (Контракт найден?) then (да)

    :Проверка требований к клиенту по 44-ФЗ
    POST/compliance/chek-44fz;

    if (Допустим такой тип БГ?) then (да)
    |Клиент|
    else (нет)
    :Отказ (Недопустимый тип БГ)
    400 Bad Request;
    stop
    endif
    
    |Система Банковской гарантии|    
    :Проверка на фрод (KYC / AML проверка)
    POST/internal/fraud-check;
    if (Проверка пройдена?) then (да)
    |Клиент|
    else (нет)
    :Отказ (Проверка не пройдена)
    400 Bad Request;
    stop
    endif
    
    |Система Банковской гарантии|        
    :Проверка банком финансовых рисков
    POST/internal/financial-risk-check;
    if (Проверка пройдена?) then (да);
    
    |Клиент|
    else (нет)
    :Отказ (Высокий риск)
    400 Bad Request;
    stop
    endif
             
    |Система Банковской гарантии|        
    :Проверка суммы и срока банковской гарантии
    POST/compliance/check-amount-term;
    if (Соответствует 44-ФЗ?) then (да)
                
                    :Рассчет комиссии за БГ;
    
    |Клиент|                
    else (нет)
    :Отказ (Нарушены сроки или сумма)
    400 Bad Request;
    stop
    endif
            
                
           
else (нет)
:Контракт не найден;
        |Клиент|
        if (Ввести данные заново?) then (да)
        
            :Ввод новых данных контракта;
        else (нет)
            :Отказ от повторного ввода данных
            204 Cancelled by user;
            stop
        endif

endif
|Система Банковской гарантии|
repeat while (Исправлять данные?) is (да)



|Клиент|
:Оплата комисии за БГ
POST/payments;

|Система Банковской гарантии|
if (Оплата получена) then (да)
    :Формирование БГ
    POST/guarantees;
    :Подписание БГ ЭЦП;
    :Подача информации в ЕИС
    POST/eis/guarantees;
    :Выдача БГ клиенту;
|Клиент|
    :Заявка одобрена
    201 Created;
    stop
else (нет)
:Оплата не получена
402 Payment Required;
stop
endif





        
    
            
                
                
            





@enduml
