@startuml
title Механика работы метода создания заявки на банковскую гарантию

|Клиент|
start
:Создание заявки;
repeat 
:Ввод данных по заявке \n (контракт, площадка размещения, сумма, срок);

|Система Банковской гарантии|
:Валидация введенных данных;


:Запрос данных о контракте в ЕИС;
if (Контракт найден?) then (да)


    :Проверка требований к клиенту по 44-ФЗ;
    if (Допустим такой тип БГ?) then (да)
    
        
        :Проверка на фрод (KYC / AML проверка);
        if (Проверка пройдена?) then (да)
            
            :Проверка банком финансовых рисков;
            if (Проверка пройдена?) then (да)
             
            
                :Проверка суммы и срока банковской гарантии;
                if (Соответствует 44-ФЗ?) then (да)
                
                    :Рассчет комиссии за БГ;
    
                    
                else (нет)
                :Отказ (Нарушены сроки или сумма);
                stop
                endif
            
            else (нет)
            :Отказ (Высокий риск);
            stop
            endif    
           
        
        else (нет)
        :Отказ (Проверка не пройдена);
        stop
        endif
    
    else (нет)
    :Отказ (Недопустимый тип БГ);
    stop
    endif
    
else (нет)
:Контракт не найден;
        |Клиент|
        if (Ввести данные заново?) then (да)
        
            :Ввод новых данных контракта;
        else (нет)
            :Отказ от повторного ввода данных;
            stop
        endif

endif
|Система Банковской гарантии|
repeat while (Исправлять данные?) is (да)



|Клиент|
:Оплата комисии за БГ;

|Система Банковской гарантии|
if (Оплата получена) then (да)
    :Формирование БГ;
    :Подписание БГ ЭЦП;
    :Подача информации в ЕИС;
    :Выдача БГ клиенту;
    stop
else (нет)
:Оплата не получена;
stop
endif





        
    
            
                
                
            





@enduml
