@startuml



skinparam linetype ortho


class User {
    _id : ObjectId
    full_name : string
    department: string
    position: string
    
}

class File {
    _id : ObjectId
    file_name : string
    file_size : integer
    file_extension : string
    file_URL : string
    upload_at : string
    upload_by : User
}


User "1" --* "1"  File 

@enduml

